"""Email conversation service.

Orchestrates the full webhook-based email conversation loop:

1. **create_from_sent_email** — called by the EMAIL node handler immediately
   after the first outbound email is dispatched.  Creates the
   ``EmailConversation`` row and the first ``EmailMessage`` (role=agent).

2. **find_conversation_by_message_id** — looks up the active conversation
   whose ``root_message_id`` or any stored ``message_id`` matches the
   ``In-Reply-To`` (or ``References``) header from the inbound webhook.
   Returns ``None`` when no match is found (e.g. spam or unrelated mail).

3. **record_inbound_reply** — stores the lead's reply as a new
   ``EmailMessage`` row (role=lead), bumps ``turn_count``, and updates
   ``last_message_id`` and ``references_chain`` on the conversation.

4. **generate_and_send_reply** — builds the full conversation context for
   the LLM (system prompt + alternating agent/lead turns), calls OpenAI,
   sends the AI reply via SMTP (with correct In-Reply-To / References
   headers), and persists the new agent message row.

5. **mark_replied_on_execution** — updates the workflow execution's
   ``node_outputs`` so the CONDITION(EMAIL_REPLIED) node evaluates to TRUE
   without needing an IMAP poll.  Each execution is updated independently
   so Lead A's reply never touches Lead B's execution.

Lead isolation
--------------
Every conversation row is keyed to a specific ``(lead_id, execution_id)``.
The inbound webhook looks up the conversation by the unique ``root_message_id``
or ``last_message_id`` from the email thread headers.  Because these IDs are
globally unique (generated by ``email.utils.make_msgid``), cross-lead
contamination is structurally impossible at the storage layer.
"""

from __future__ import annotations

import asyncio
import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from common.logging import get_logger

if TYPE_CHECKING:
    from sqlalchemy.orm import Session
    from modules.campaign.email_conversation_model import EmailConversation

log = get_logger("campaign.email_conversation_service")

_MAX_HISTORY_TURNS = 10  # How many prior turns to include in LLM context
_MAX_REPLY_TOKENS = 512   # Max tokens for the AI reply email


# ---------------------------------------------------------------------------
# Public service
# ---------------------------------------------------------------------------


class EmailConversationService:

    # ------------------------------------------------------------------ #
    # Create conversation on first send
    # ------------------------------------------------------------------ #

    @staticmethod
    def create_from_sent_email(
        db: "Session",
        *,
        lead_id: uuid.UUID,
        organization_id: uuid.UUID,
        execution_id: uuid.UUID | None,
        campaign_id: uuid.UUID | None,
        message_id: str,
        subject: str,
        body: str,
        lead_email: str,
    ) -> "EmailConversation":
        """Create a new EmailConversation + first EmailMessage (agent) row.

        Called from EmailNodeHandler after a successful SMTP send so every
        outbound email has a thread record ready to match incoming replies.
        """
        from modules.campaign.email_conversation_model import (
            EmailConversation,
            EmailMessage,
            ROLE_AGENT,
        )

        now = datetime.now(timezone.utc)

        conv = EmailConversation(
            organization_id=organization_id,
            lead_id=lead_id,
            execution_id=execution_id,
            campaign_id=campaign_id,
            root_message_id=message_id,
            last_message_id=message_id,
            references_chain=message_id,
            subject=subject,
            lead_email=lead_email,
            status="active",
            turn_count=0,
        )
        db.add(conv)
        db.flush()

        msg_row = EmailMessage(
            conversation_id=conv.id,
            organization_id=organization_id,
            lead_id=lead_id,
            role=ROLE_AGENT,
            message_id=message_id,
            in_reply_to=None,
            references=None,
            subject=subject,
            body=body,
            sent_at=now,
        )
        db.add(msg_row)
        db.flush()

        log.info(
            "email_conversation.created",
            conversation_id=str(conv.id),
            lead_id=str(lead_id),
            message_id=message_id,
        )
        return conv

    # ------------------------------------------------------------------ #
    # Lookup by inbound header
    # ------------------------------------------------------------------ #

    @staticmethod
    def find_conversation_by_message_id(
        db: "Session",
        *,
        message_id: str,
    ) -> "EmailConversation | None":
        """Find the active conversation that owns *message_id*.

        Searches both ``root_message_id`` and ``last_message_id``.  For
        long threads where the lead's client only preserves the most recent
        ``In-Reply-To`` this covers both the common first-reply case and
        subsequent turns.
        """
        from sqlalchemy import or_
        from modules.campaign.email_conversation_model import EmailConversation

        clean = message_id.strip()
        conv = (
            db.query(EmailConversation)
            .filter(
                EmailConversation.status == "active",
                or_(
                    EmailConversation.root_message_id == clean,
                    EmailConversation.last_message_id == clean,
                ),
            )
            .order_by(EmailConversation.created_at.desc())
            .first()
        )
        return conv

    @staticmethod
    def find_conversation_by_references(
        db: "Session",
        *,
        references: str,
    ) -> "EmailConversation | None":
        """Fallback: scan active conversations to see if any stored Message-ID
        appears in the inbound References header chain."""
        from modules.campaign.email_conversation_model import EmailConversation

        # References is a space-separated list of Message-IDs.
        ref_ids = [r.strip() for r in references.split() if r.strip()]
        if not ref_ids:
            return None

        for ref_id in ref_ids:
            conv = (
                db.query(EmailConversation)
                .filter(
                    EmailConversation.status == "active",
                    EmailConversation.root_message_id == ref_id,
                )
                .order_by(EmailConversation.created_at.desc())
                .first()
            )
            if conv:
                return conv
        return None

    # ------------------------------------------------------------------ #
    # Store inbound reply
    # ------------------------------------------------------------------ #

    @staticmethod
    def record_inbound_reply(
        db: "Session",
        *,
        conversation: "EmailConversation",
        message_id: str,
        in_reply_to: str | None,
        references: str | None,
        subject: str,
        body: str,
    ) -> None:
        """Persist the lead's incoming reply and update thread state.

        Updates ``last_message_id``, ``references_chain``, and
        ``turn_count`` on the conversation, then writes the new
        ``EmailMessage`` row.
        """
        from modules.campaign.email_conversation_model import EmailMessage, ROLE_LEAD

        now = datetime.now(timezone.utc)

        # Append the new Message-ID to the references chain.
        existing_refs = (conversation.references_chain or "").strip()
        new_refs = f"{existing_refs} {message_id}".strip()

        conversation.last_message_id = message_id
        conversation.references_chain = new_refs
        conversation.turn_count = (conversation.turn_count or 0) + 1
        db.flush()

        msg_row = EmailMessage(
            conversation_id=conversation.id,
            organization_id=conversation.organization_id,
            lead_id=conversation.lead_id,
            role=ROLE_LEAD,
            message_id=message_id,
            in_reply_to=in_reply_to,
            references=references,
            subject=subject,
            body=body[:5000],  # guard against excessively large payloads
            sent_at=now,
        )
        db.add(msg_row)
        db.flush()

        log.info(
            "email_conversation.reply_recorded",
            conversation_id=str(conversation.id),
            lead_id=str(conversation.lead_id),
            turn_count=conversation.turn_count,
            message_id=message_id,
        )

    # ------------------------------------------------------------------ #
    # Mark execution as replied (for CONDITION node)
    # ------------------------------------------------------------------ #

    @staticmethod
    def mark_replied_on_execution(
        db: "Session",
        *,
        execution_id: uuid.UUID,
        reply_subject: str,
        reply_body: str,
        replied_at: str,
    ) -> None:
        """Update node_outputs on the execution so CONDITION(EMAIL_REPLIED) = TRUE.

        The CONDITION handler checks ``source_output["replied"]`` first and
        skips the IMAP poll when this flag is already True.  This is per-lead
        because each lead has its own execution row.
        """
        from modules.campaign.execution_model import Execution

        execution = db.get(Execution, execution_id)
        if execution is None:
            log.warning(
                "email_conversation.mark_replied.execution_not_found",
                execution_id=str(execution_id),
            )
            return

        node_outputs: dict = dict(execution.node_outputs or {})

        # Find the EMAIL node output to enrich — it's the one with a
        # ``message_id`` key (set by EmailNodeHandler).
        email_node_id: str | None = None
        for nid, output in node_outputs.items():
            if isinstance(output, dict) and output.get("message_id"):
                email_node_id = nid
                break

        if email_node_id is None:
            log.warning(
                "email_conversation.mark_replied.no_email_node_output",
                execution_id=str(execution_id),
            )
            return

        node_outputs[email_node_id].update(
            {
                "replied": True,
                "within_window": True,
                "replied_at": replied_at,
                "reply_subject": reply_subject,
                "reply_body": reply_body[:500],
                "match_method": "webhook",
            }
        )
        execution.node_outputs = node_outputs
        db.flush()

        log.info(
            "email_conversation.mark_replied.execution_updated",
            execution_id=str(execution_id),
            email_node_id=email_node_id,
        )

    # ------------------------------------------------------------------ #
    # Emit reply_recv LeadActivity
    # ------------------------------------------------------------------ #

    @staticmethod
    def emit_reply_received_activity(
        db: "Session",
        *,
        lead_id: uuid.UUID,
        organization_id: uuid.UUID,
        reply_subject: str,
        reply_body: str,
    ) -> None:
        """Write a reply_recv LeadActivity row for the audit trail."""
        from modules.leads.model import ACTIVITY_REPLY_RECEIVED, LeadActivity

        activity = LeadActivity(
            organization_id=organization_id,
            lead_id=lead_id,
            activity_type=ACTIVITY_REPLY_RECEIVED,
            notes=(
                f"Inbound reply via webhook. "
                f"Subject: {reply_subject!r}. "
                f"Preview: {reply_body[:200]}"
            ),
        )
        db.add(activity)
        db.flush()

    # ------------------------------------------------------------------ #
    # Generate AI reply and send
    # ------------------------------------------------------------------ #

    @staticmethod
    async def generate_and_send_reply(
        db: "Session",
        *,
        conversation: "EmailConversation",
        inbound_body: str,
        inbound_subject: str,
    ) -> dict:
        """Generate an LLM reply and send it via SMTP.

        Builds conversation context (all prior turns), calls OpenAI, sends
        the reply with correct In-Reply-To / References headers to maintain
        thread continuity, and persists the new agent message row.

        Returns a result dict with keys:
        ``sent`` (bool), ``message_id`` (str | None), ``error`` (str | None).
        """
        # ── Guard: max_turns reached → close conversation ─────────────
        if (conversation.turn_count or 0) >= (conversation.max_turns or 10):
            conversation.status = "closed"
            db.flush()
            log.info(
                "email_conversation.max_turns_reached",
                conversation_id=str(conversation.id),
                turn_count=conversation.turn_count,
            )
            return {"sent": False, "message_id": None, "error": "max_turns_reached"}

        # ── Build conversation history for the LLM ────────────────────
        messages = EmailConversationService._build_llm_messages(
            db, conversation=conversation
        )

        # ── Call OpenAI ───────────────────────────────────────────────
        try:
            reply_text = await EmailConversationService._call_openai(messages)
        except Exception as exc:
            log.error(
                "email_conversation.openai_failed",
                conversation_id=str(conversation.id),
                error=str(exc),
            )
            return {"sent": False, "message_id": None, "error": str(exc)}

        # ── Compose reply subject (keep "Re:" prefix exactly once) ────
        subj = inbound_subject.strip()
        if not subj.lower().startswith("re:"):
            reply_subject = f"Re: {conversation.subject}"
        else:
            reply_subject = subj

        # ── Send via SMTP (run sync call in thread-pool) ───────────────
        in_reply_to = conversation.last_message_id
        references = conversation.references_chain

        try:
            loop = asyncio.get_event_loop()
            result_meta = await loop.run_in_executor(
                None,
                lambda: _smtp_send_reply(
                    to=conversation.lead_email,
                    subject=reply_subject,
                    body=reply_text,
                    in_reply_to=in_reply_to,
                    references=references,
                ),
            )
        except Exception as exc:
            log.error(
                "email_conversation.smtp_failed",
                conversation_id=str(conversation.id),
                error=str(exc),
            )
            return {"sent": False, "message_id": None, "error": str(exc)}

        new_message_id: str = result_meta["message_id"]
        now_str = datetime.now(timezone.utc).isoformat()

        # ── Persist new agent message + update conversation ───────────
        from modules.campaign.email_conversation_model import (
            EmailMessage,
            ROLE_AGENT,
        )

        new_refs = f"{(conversation.references_chain or '').strip()} {new_message_id}".strip()
        conversation.last_message_id = new_message_id
        conversation.references_chain = new_refs
        db.flush()

        msg_row = EmailMessage(
            conversation_id=conversation.id,
            organization_id=conversation.organization_id,
            lead_id=conversation.lead_id,
            role=ROLE_AGENT,
            message_id=new_message_id,
            in_reply_to=in_reply_to,
            references=references,
            subject=reply_subject,
            body=reply_text,
            sent_at=datetime.now(timezone.utc),
        )
        db.add(msg_row)
        db.flush()

        log.info(
            "email_conversation.ai_reply_sent",
            conversation_id=str(conversation.id),
            lead_id=str(conversation.lead_id),
            new_message_id=new_message_id,
            reply_length=len(reply_text),
        )
        return {"sent": True, "message_id": new_message_id, "error": None}

    # ------------------------------------------------------------------ #
    # LLM context builder
    # ------------------------------------------------------------------ #

    @staticmethod
    def _build_llm_messages(
        db: "Session",
        *,
        conversation: "EmailConversation",
    ) -> list[dict]:
        """Build the OpenAI messages list from the stored conversation history.

        Returns a list of ``{"role": str, "content": str}`` dicts ready to
        pass to ``openai.chat.completions.create``.
        """
        from modules.campaign.email_conversation_model import (
            EmailMessage,
            ROLE_AGENT,
        )

        system_prompt = (
            "You are a professional sales development representative (SDR) "
            "continuing an email conversation with a prospect. "
            "Keep replies concise (2-4 sentences), friendly, and focused on "
            "moving the deal forward. Never mention that you are an AI. "
            "Match the tone of the prospect's last message. "
            "Do not include a subject line in your reply — write only the body."
        )

        # Load the most recent _MAX_HISTORY_TURNS turns from DB.
        history_msgs = (
            db.query(EmailMessage)
            .filter(EmailMessage.conversation_id == conversation.id)
            .order_by(EmailMessage.sent_at.asc())
            .limit(_MAX_HISTORY_TURNS * 2)
            .all()
        )

        messages: list[dict] = [{"role": "system", "content": system_prompt}]
        for m in history_msgs:
            role = "assistant" if m.role == ROLE_AGENT else "user"
            messages.append({"role": role, "content": m.body})

        return messages

    # ------------------------------------------------------------------ #
    # OpenAI call helper (uses raw openai SDK to stay self-contained)
    # ------------------------------------------------------------------ #

    @staticmethod
    async def _call_openai(messages: list[dict]) -> str:
        """Call OpenAI chat completions and return the reply text."""
        from openai import AsyncOpenAI
        from config.settings import settings

        if not settings.OPENAI_API_KEY:
            raise RuntimeError("OPENAI_API_KEY is not configured")

        client = AsyncOpenAI(
            api_key=settings.OPENAI_API_KEY,
            base_url=settings.OPENAI_BASE_URL or None,
            timeout=settings.OPENAI_TIMEOUT_SECONDS,
            max_retries=settings.OPENAI_MAX_RETRIES,
        )
        try:
            resp = await client.chat.completions.create(
                model=settings.OPENAI_MODEL,
                messages=messages,  # type: ignore[arg-type]
                temperature=0.5,
                max_tokens=_MAX_REPLY_TOKENS,
            )
            return (resp.choices[0].message.content or "").strip()
        finally:
            await client.close()


# ---------------------------------------------------------------------------
# Module-level SMTP helper (sync, called from thread-pool executor)
# ---------------------------------------------------------------------------


def _smtp_send_reply(
    *,
    to: str,
    subject: str,
    body: str,
    in_reply_to: str,
    references: str,
) -> dict:
    """Thin wrapper around the mailer for AI-generated replies."""
    from common.email.mailer import send_email

    return send_email(
        to=to,
        subject=subject,
        text_body=body,
        in_reply_to=in_reply_to,
        references=references,
    )
