"""Inbound email webhook endpoint.

Receives parsed inbound emails from SendGrid Inbound Parse, Mailgun Routes,
or any generic provider that POSTs form-encoded or JSON payloads.

Endpoint
--------
``POST /api/v1/inbound/email``

No authentication header is required (the route must be publicly reachable
by the email provider).  Optional HMAC/secret-key verification is performed
when ``INBOUND_EMAIL_WEBHOOK_SECRET`` is set in the environment.

Supported providers
-------------------
* **SendGrid Inbound Parse** — sends ``multipart/form-data`` with fields
  ``from``, ``subject``, ``text``, ``html``, ``headers`` (raw header block),
  ``envelope`` (JSON sender/recipient metadata).
* **Mailgun Routes** — sends ``multipart/form-data`` with fields
  ``From``, ``Subject``, ``body-plain``, ``Message-Id``, ``In-Reply-To``,
  ``References``, ``recipient``.
* **Generic JSON** — a JSON body with keys ``from``, ``subject``, ``body``,
  ``message_id``, ``in_reply_to``, ``references``.

Provider detection is heuristic: SendGrid includes an ``envelope`` field,
Mailgun includes a ``body-plain`` field, everything else is treated as
generic JSON.

Security
--------
Set ``INBOUND_EMAIL_WEBHOOK_SECRET`` in ``.env``.  When set:
- SendGrid: the value should match ``X-Webhook-Secret`` header.
- Mailgun: the handler verifies the HMAC-SHA256 signature using
  ``timestamp``, ``token``, and ``signature`` fields in the payload.
- Generic: the value should match the ``X-Webhook-Secret`` header.

When the secret is not set the endpoint accepts all requests (suitable for
development; use network-level access control in production).

Per-lead isolation guarantee
----------------------------
The webhook matches the inbound email to an ``EmailConversation`` via the
``In-Reply-To`` or ``References`` header, which contains a globally unique
``Message-ID`` generated by ``email.utils.make_msgid``.  Each conversation
is keyed to a specific ``(lead_id, execution_id)`` so a reply from Lead A
can never affect Lead B's workflow execution.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends, Header, HTTPException, Request, status
from sqlalchemy.orm import Session

from common.logging import get_logger
from config.settings import settings
from database.dependencies import get_db

log = get_logger("campaign.inbound_email")

router = APIRouter(prefix="/inbound", tags=["inbound-email"])


# ---------------------------------------------------------------------------
# Main webhook handler
# ---------------------------------------------------------------------------


@router.post(
    "/email",
    status_code=status.HTTP_200_OK,
    summary="Receive inbound email reply (webhook)",
)
async def receive_inbound_email(
    request: Request,
    db: Session = Depends(get_db),
    x_webhook_secret: str | None = Header(default=None, alias="X-Webhook-Secret"),
) -> dict:
    """Process an inbound email reply delivered by SendGrid/Mailgun/generic.

    1. Verifies webhook secret (when configured).
    2. Parses provider-specific payload into a normalised ``InboundEmail``.
    3. Matches the message to an active ``EmailConversation`` via
       ``In-Reply-To`` / ``References`` headers.
    4. Stores the reply in the database.
    5. Updates the workflow execution so ``CONDITION(EMAIL_REPLIED)`` → TRUE.
    6. Generates an AI reply via OpenAI and sends it via SMTP.
    7. Emits a ``reply_recv`` ``LeadActivity`` row for the audit trail.
    """
    content_type = request.headers.get("content-type", "")

    # ── Parse payload ─────────────────────────────────────────────────────
    if "multipart/form-data" in content_type or "application/x-www-form-urlencoded" in content_type:
        form = await request.form()
        payload: dict[str, Any] = dict(form)
        body_bytes: bytes | None = None
    else:
        body_bytes = await request.body()
        try:
            payload = json.loads(body_bytes)
        except Exception:
            payload = {}

    # ── Verify secret ─────────────────────────────────────────────────────
    secret = settings.INBOUND_EMAIL_WEBHOOK_SECRET
    if secret:
        _verify_secret(
            secret=secret,
            payload=payload,
            x_webhook_secret=x_webhook_secret,
            raw_body=body_bytes,
        )

    # ── Normalise ─────────────────────────────────────────────────────────
    inbound = _parse_payload(payload)

    if not inbound.get("in_reply_to") and not inbound.get("references"):
        log.info(
            "inbound_email.no_thread_headers",
            from_email=inbound.get("from_email"),
            subject=inbound.get("subject"),
        )
        return {"status": "ignored", "reason": "no_thread_headers"}

    log.info(
        "inbound_email.received",
        from_email=inbound.get("from_email"),
        subject=inbound.get("subject"),
        in_reply_to=inbound.get("in_reply_to"),
        message_id=inbound.get("message_id"),
    )

    # ── Match conversation ────────────────────────────────────────────────
    from modules.campaign.email_conversation_service import (
        EmailConversationService,
    )

    conversation = None

    in_reply_to = inbound.get("in_reply_to", "").strip()
    references = inbound.get("references", "").strip()

    if in_reply_to:
        conversation = EmailConversationService.find_conversation_by_message_id(
            db, message_id=in_reply_to
        )

    if conversation is None and references:
        conversation = EmailConversationService.find_conversation_by_references(
            db, references=references
        )

    if conversation is None:
        log.info(
            "inbound_email.no_conversation_match",
            in_reply_to=in_reply_to,
            references=references[:120] if references else "",
        )
        return {"status": "ignored", "reason": "no_conversation_match"}

    # ── Check negative / opt-out intent before doing anything else ────────
    from modules.campaign.email_reply_service import _is_negative_reply

    reply_body: str = inbound.get("body", "")
    reply_subject: str = inbound.get("subject", "")
    inbound_message_id: str = inbound.get("message_id", "")

    is_negative = _is_negative_reply(reply_subject + " " + reply_body)
    if is_negative:
        _handle_negative_reply(db, conversation=conversation, reply_body=reply_body, reply_subject=reply_subject)
        db.commit()
        log.info(
            "inbound_email.negative_reply",
            conversation_id=str(conversation.id),
            lead_id=str(conversation.lead_id),
        )
        return {"status": "ok", "action": "negative_reply_handled"}

    replied_at = datetime.now(timezone.utc).isoformat()

    # ── Store inbound message ─────────────────────────────────────────────
    EmailConversationService.record_inbound_reply(
        db,
        conversation=conversation,
        message_id=inbound_message_id or _synthetic_message_id(),
        in_reply_to=in_reply_to or None,
        references=references or None,
        subject=reply_subject,
        body=reply_body,
    )

    # ── Emit reply_recv activity ──────────────────────────────────────────
    EmailConversationService.emit_reply_received_activity(
        db,
        lead_id=conversation.lead_id,
        organization_id=conversation.organization_id,
        reply_subject=reply_subject,
        reply_body=reply_body,
    )

    # ── Mark execution as replied (unblocks CONDITION node) ───────────────
    if conversation.execution_id:
        EmailConversationService.mark_replied_on_execution(
            db,
            execution_id=conversation.execution_id,
            reply_subject=reply_subject,
            reply_body=reply_body[:500],
            replied_at=replied_at,
        )

    db.commit()

    # ── Generate & send AI reply (async — after DB commit) ────────────────
    try:
        reply_result = await EmailConversationService.generate_and_send_reply(
            db,
            conversation=conversation,
            inbound_body=reply_body,
            inbound_subject=reply_subject,
        )
        db.commit()
        log.info(
            "inbound_email.ai_reply_result",
            conversation_id=str(conversation.id),
            sent=reply_result.get("sent"),
            message_id=reply_result.get("message_id"),
            error=reply_result.get("error"),
        )
    except Exception as exc:
        db.rollback()
        log.error(
            "inbound_email.ai_reply_error",
            conversation_id=str(conversation.id),
            error=str(exc),
        )
        return {
            "status": "partial",
            "reply_stored": True,
            "ai_reply_sent": False,
            "error": str(exc),
        }

    return {
        "status": "ok",
        "conversation_id": str(conversation.id),
        "reply_stored": True,
        "ai_reply_sent": reply_result.get("sent", False),
    }


# ---------------------------------------------------------------------------
# Negative-reply handler
# ---------------------------------------------------------------------------


def _handle_negative_reply(
    db: Session,
    *,
    conversation: Any,
    reply_body: str,
    reply_subject: str,
) -> None:
    """Close conversation and mark lead as lost on opt-out."""
    import uuid as _uuid
    from modules.leads.model import (
        Lead,
        LeadActivity,
        LEAD_STATUS_LOST,
        ACTIVITY_REPLY_NEGATIVE,
    )

    conversation.status = "closed"
    db.flush()

    lead = db.get(Lead, conversation.lead_id)
    if lead and lead.status != LEAD_STATUS_LOST:
        lead.status = LEAD_STATUS_LOST
        db.flush()

    db.add(
        LeadActivity(
            organization_id=conversation.organization_id,
            lead_id=conversation.lead_id,
            activity_type=ACTIVITY_REPLY_NEGATIVE,
            notes=(
                f"Negative reply via webhook. "
                f"Subject: {reply_subject!r}. "
                f"Preview: {reply_body[:200]}"
            ),
        )
    )
    db.flush()


# ---------------------------------------------------------------------------
# Payload parsers
# ---------------------------------------------------------------------------


def _parse_payload(payload: dict) -> dict:
    """Detect provider and extract normalised email fields."""

    # SendGrid Inbound Parse detection: has "envelope" field.
    if "envelope" in payload:
        return _parse_sendgrid(payload)

    # Mailgun detection: has "body-plain" or "Mailgun-Variables" field.
    if "body-plain" in payload or "Mailgun-Variables" in payload:
        return _parse_mailgun(payload)

    # Generic / custom JSON format.
    return _parse_generic(payload)


def _extract_header_from_block(raw_headers: str, name: str) -> str:
    """Extract a header value from a raw RFC 2822 header block string."""
    lower_name = name.lower() + ":"
    for line in raw_headers.splitlines():
        if line.lower().startswith(lower_name):
            return line[len(lower_name):].strip()
    return ""


def _parse_sendgrid(payload: dict) -> dict:
    """Parse a SendGrid Inbound Parse multipart/form-data payload."""
    raw_headers: str = payload.get("headers", "") or ""

    # SendGrid sends parsed header values separately in newer API versions.
    in_reply_to = (
        payload.get("in-reply-to")
        or payload.get("In-Reply-To")
        or _extract_header_from_block(raw_headers, "In-Reply-To")
    )
    references = (
        payload.get("references")
        or payload.get("References")
        or _extract_header_from_block(raw_headers, "References")
    )
    message_id = (
        payload.get("message-id")
        or payload.get("Message-Id")
        or _extract_header_from_block(raw_headers, "Message-ID")
    )

    return {
        "from_email": _extract_email(str(payload.get("from") or "")),
        "subject": str(payload.get("subject") or ""),
        "body": str(payload.get("text") or payload.get("html") or ""),
        "message_id": message_id,
        "in_reply_to": in_reply_to,
        "references": references,
    }


def _parse_mailgun(payload: dict) -> dict:
    """Parse a Mailgun Routes multipart/form-data payload."""
    return {
        "from_email": _extract_email(str(payload.get("From") or payload.get("from") or "")),
        "subject": str(payload.get("Subject") or payload.get("subject") or ""),
        "body": str(payload.get("body-plain") or payload.get("stripped-text") or ""),
        "message_id": str(payload.get("Message-Id") or payload.get("message-id") or ""),
        "in_reply_to": str(payload.get("In-Reply-To") or payload.get("in-reply-to") or ""),
        "references": str(payload.get("References") or payload.get("references") or ""),
    }


def _parse_generic(payload: dict) -> dict:
    """Parse a generic JSON inbound webhook payload."""
    return {
        "from_email": _extract_email(str(payload.get("from") or "")),
        "subject": str(payload.get("subject") or ""),
        "body": str(payload.get("body") or payload.get("text") or ""),
        "message_id": str(payload.get("message_id") or payload.get("message-id") or ""),
        "in_reply_to": str(payload.get("in_reply_to") or payload.get("In-Reply-To") or ""),
        "references": str(payload.get("references") or payload.get("References") or ""),
    }


def _extract_email(value: str) -> str:
    """Extract the bare email address from a display-name+address string."""
    import re
    m = re.search(r"<([^>]+)>", value)
    if m:
        return m.group(1).strip()
    return value.strip()


# ---------------------------------------------------------------------------
# Secret verification
# ---------------------------------------------------------------------------


def _verify_secret(
    *,
    secret: str,
    payload: dict,
    x_webhook_secret: str | None,
    raw_body: bytes | None,
) -> None:
    """Raise 401 when the webhook secret does not match.

    For Mailgun payloads, verifies the HMAC-SHA256 signature using the
    ``timestamp``, ``token``, and ``signature`` fields.  For all other
    providers, verifies the ``X-Webhook-Secret`` header against the
    configured secret.
    """
    # Mailgun HMAC verification.
    if "token" in payload and "timestamp" in payload and "signature" in payload:
        expected = hmac.HMAC(
            secret.encode(),
            msg=(
                str(payload.get("timestamp", ""))
                + str(payload.get("token", ""))
            ).encode(),
            digestmod=hashlib.sha256,
        ).hexdigest()
        if not hmac.compare_digest(expected, str(payload.get("signature", ""))):
            log.warning("inbound_email.mailgun_signature_invalid")
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid Mailgun webhook signature",
            )
        return

    # Generic / SendGrid: compare X-Webhook-Secret header.
    if x_webhook_secret is None:
        log.warning("inbound_email.missing_secret_header")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing X-Webhook-Secret header",
        )
    if not hmac.compare_digest(x_webhook_secret, secret):
        log.warning("inbound_email.invalid_secret_header")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid X-Webhook-Secret header",
        )


def _synthetic_message_id() -> str:
    """Generate a fallback Message-ID when the inbound payload omits one."""
    from email.utils import make_msgid
    return make_msgid(domain="inbound.aifficient.co")
