"""create_ai_tables

Revision ID: 9fc7dd0db59a
Revises: 5b255768ae28
Create Date: 2026-05-29 09:50:53.855387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc7dd0db59a'
down_revision: Union[str, Sequence[str], None] = '5b255768ae28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_summaries',
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('qualification_status', sa.String(length=32), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.JSON(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_summaries_call_id'), 'ai_call_summaries', ['call_id'], unique=True)
    op.create_index(op.f('ix_ai_call_summaries_organization_id'), 'ai_call_summaries', ['organization_id'], unique=False)
    op.create_table('ai_calls',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('persona', sa.String(length=64), nullable=True),
    sa.Column('framework', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_calls_call_id'), 'ai_calls', ['call_id'], unique=True)
    op.create_index(op.f('ix_ai_calls_organization_id'), 'ai_calls', ['organization_id'], unique=False)
    op.create_table('ai_transcript_entries',
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_transcript_call_turn', 'ai_transcript_entries', ['call_id', 'turn_index'], unique=False)
    op.create_index(op.f('ix_ai_transcript_entries_call_id'), 'ai_transcript_entries', ['call_id'], unique=False)
    op.create_index(op.f('ix_ai_transcript_entries_organization_id'), 'ai_transcript_entries', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_transcript_entries_organization_id'), table_name='ai_transcript_entries')
    op.drop_index(op.f('ix_ai_transcript_entries_call_id'), table_name='ai_transcript_entries')
    op.drop_index('ix_ai_transcript_call_turn', table_name='ai_transcript_entries')
    op.drop_table('ai_transcript_entries')
    op.drop_index(op.f('ix_ai_calls_organization_id'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_call_id'), table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_index(op.f('ix_ai_call_summaries_organization_id'), table_name='ai_call_summaries')
    op.drop_index(op.f('ix_ai_call_summaries_call_id'), table_name='ai_call_summaries')
    op.drop_table('ai_call_summaries')
    # ### end Alembic commands ###
