# """add role enum

# Revision ID: c93024405c80
# Revises: b760b083ac85
# Create Date: 2026-05-27 07:10:53.594287

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'c93024405c80'
# down_revision: Union[str, Sequence[str], None] = 'b760b083ac85'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('memberships', 'role',
#                existing_type=sa.VARCHAR(length=50),
#                type_=sa.Enum('OWNER', 'ADMIN', 'AGENT', 'MEMBER', name='role'),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('memberships', 'role',
#                existing_type=sa.Enum('OWNER', 'ADMIN', 'AGENT', 'MEMBER', name='role'),
#                type_=sa.VARCHAR(length=50),
#                existing_nullable=False)
#     # ### end Alembic commands ###



from alembic import op
import sqlalchemy as sa

revision = 'c93024405c80'
down_revision = 'b760b083ac85'
branch_labels = None
depends_on = None

role_enum = sa.Enum('owner', 'admin', 'agent', 'member', name='role')


def upgrade() -> None:
    role_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'memberships', 'role',
        existing_type=sa.VARCHAR(length=50),
        type_=role_enum,
        existing_nullable=False,
        postgresql_using='role::role',
    )


def downgrade() -> None:
    op.alter_column(
        'memberships', 'role',
        existing_type=role_enum,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using='role::text',
    )
    role_enum.drop(op.get_bind(), checkfirst=True)